version: "3.9"

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ganapatih
      POSTGRES_PASSWORD: ganapatih
      POSTGRES_DB: ganapatih_db
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
    environment:
      NODE_ENV: development
      PORT: 5001

      POSTGRES_USER: ganapatih
      POSTGRES_PASSWORD: ganapatih
      POSTGRES_DB: ganapatih_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

      ACCESS_TOKEN_SECRET: ganpaatih_access_token_secret
      REFRESH_TOKEN_SECRET: ganapatih_refresh_token_secret

    depends_on:
      - db

    command: >
      sh -c "
      echo 'Waiting for Postgres...' &&
      until nc -z db 5432; do sleep 1; done &&
      echo 'Postgres is ready!' &&

      echo 'Running Sequelize migrations + seeders...' &&
      npx sequelize-cli db:migrate &&
      npx sequelize-cli db:seed:all &&

      echo 'Starting server...' &&
      npm run start
      "

    ports:
      - "5001:5001"

  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:5001/api
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: http://localhost:5001/api
    depends_on:
      - server
    ports:
      - "3000:3000"

volumes:
  postgres-data:
    name: postgres-data
