openapi: 3.1.0
info:
  title: API Docs
  version: 1.0.0
  description: User REST API
servers:
  - url: http://localhost:${PORT}/api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
